site_name: MusicPimp
site_author: Michael Skogberg

theme:
  name: 'material'

nav:
  - Develop: index.md
  - Http Endpoints: http-endpoints.md
  - Server Events: server-events.md
  - Code Samples: code-samples.md

copyright: Copyright &copy; 2019 <a href="https://github.com/malliina">Michael Skogberg</a>
