name: Test

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Set up Netlify
        uses: netlify/actions/cli@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2
      - name: Download and install SBT
        env:
          SBT_VERSION: 1.3.4
        run: |
          curl -L -o sbt-${SBT_VERSION}.deb https://dl.bintray.com/sbt/debian/sbt-${SBT_VERSION}.deb
          sudo dpkg -i sbt-${SBT_VERSION}.deb
      - name: Install MkDocs and Material theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
      - name: Install Netlify CLI
        run: |
          npm install netlify-cli -g
      - name: Run tests
        run: sbt test
      - name: Build site
        run: sbt buildAndDeploy
